name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version of the app to be released"
      deploy_on_success:
        type: boolean
        default: false
        description: "Automatic deployment on success"

jobs:
  git-release:
    uses: sylvanld/github-workflows/.github/workflows/git-tag.yml@main
    with:
      git_tag: ${{ inputs.version }}
      run_before: |
        sed -i 's|X.Y.Z|${{ inputs.version }}|g' cookbook/api/metadata.py
        git add cookbook/api/metadata.py

  docker-release:
    needs: git-release
    uses: sylvanld/github-workflows/.github/workflows/docker-release.yml@main
    secrets: inherit
    with:
      git_tag: ${{ inputs.version }}
      docker_image_name: sylvanld/cookbook-api
      docker_image_tags: ${{ inputs.version }}

  deploy:
    needs: docker-release
    if: inputs.deploy_on_success
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
